ClinicManagementProject-main/Models/ClinicManagementContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using ClinicManagementProject.Models;

namespace ClinicManagementProject.Models
{
    public class ClinicManagementContext : DbContext
    {
        public ClinicManagementContext(DbContextOptions options) : base(options)//taking options from base
        {

        }

        public DbSet<Doctor> Doctors { get; set; }
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            
            modelBuilder.Entity<Doctor>().HasData(
                new Doctor()
                {
                    Doctor_Id = 1,
                    Username = "docabc",
                    Name = "TimDoc",
                    Age = 30,
                    Phone = "323524523",
                    Gender = "Male",
                    Password = new byte[1],
                    PasswordSalt = new byte[1] //just a place holder password to prevent exception..
                });
            modelBuilder.Entity<Doctor>().HasData(
                new Doctor()
                {
                    Doctor_Id = 2,
                    Username = "docoof",
                    Name = "TiDoc",
                    Age = 30,
                    Phone = "323524523",
                    Gender = "Male",
                    Password = new byte[2],
                    PasswordSalt = new byte[2] //just a place holder password to prevent exception..
                });
        }
        //public DbSet<ClinicManagementProject.Models.DoctorSchedule> DoctorSchedule { get; set; }
    }
}

ClinicManagementProject-main/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ClinicManagementProject.Models
{
    public class Doctor
    {
        [Key] 
        public int Doctor_Id { get; set; }

        //username and password
        //[Required(ErrorMessage = "Username cannot be empty")]
        public string Username { get; set; }//validation done in patient register controller, so wont allowed to be repeated

        public byte[] Password { get; set; } //since passing to database, cannot be seen, must be encrypted
        public byte[] PasswordSalt { get; set; }//salt for encryption, passed to database as well

        //Doctor info
        //[Required(ErrorMessage = "Name cannot be empty")]
        public string Name { get; set; }
        //[Required(ErrorMessage = "Gender cannot be empty")]
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Phone { get; set; }
        public string Specialization { get; set; }
                
    }
}

ClinicManagementProject-main/Controllers/DoctorController.cs
using ClinicManagementProject.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ClinicManagementProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClinicManagementProject.Controllers
{
    public class DoctorController : Controller
    {
        //private readonly ILogger<ClinicManagementContext> _logger;
        private readonly ILogger<DoctorController> _logger;
        private readonly IRepo<Doctor, string> _repo;

        public DoctorController(IRepo<Doctor, string> repo, ILogger<DoctorController> logger)
        {
            _logger = logger;
            _repo = repo;
        }

        
        public async Task<ActionResult> Index()
        {
            var doctors = await _repo.GetAll();
            return View(doctors);
        }

        
        public async Task<ActionResult> Details(int id)
        {
            try
            {
                Doctor doctor = await _repo.Get(id);
                return View(doctor);
            }
            catch
            {
                _logger.LogError("Uable to get the edit");
            }
            return View();
        }

        // GET:DoctroController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST:DoctroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Doctor doctor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                      var id = await _repo.Add(doctor);
                    if (id.Doctor_Id!= -1)
                        return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
            return View();
        }


        public async Task<ActionResult> Edit(int id)
        {

            try
            {
                Doctor doctor = await _repo.Get(id);
                return View(doctor);
            }
            catch
            {
                _logger.LogError("Uable to get the edit");
            }
            return View();

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Doctor doctor) //not getting doctor Id for some reason, nor id
        {
            try
            {
               
                Doctor myDoctor = await _repo.Update(id, doctor);
                //Doctor myDoctor = await _repo.Update(id, doctor);
                if (myDoctor != null)
                    return RedirectToAction("Index");
            }
            catch
            {
                return View("Edit", doctor);
            }
            return View("Edit", doctor);
        }

        
        public ActionResult Delete(int id)
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ClinicManagementProject-main/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClinicManagementProject.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClinicManagementProject-main/Views/Doctor/Create.cshtml
@model ClinicManagementProject.Models.Doctor

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/bootstrap.css" rel="stylesheet" />
    <title>Create</title>
</head>
<body>

    <h4>Doctor</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            @using (Html.BeginForm("Create", "Doctor", FormMethod.Post))
            {
                @Html.LabelFor(m => m.Username, htmlAttributes: new { @class = "form-control" })
                @Html.EditorFor(m => m.Username, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(m => m.Name, htmlAttributes: new { @class = "form-control" })
                @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(m => m.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.EditorFor(m => m.Gender, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(m => m.Age, htmlAttributes: new { @class = "form-control" })
                @Html.EditorFor(m => m.Age, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(m => m.Phone, htmlAttributes: new { @class = "form-control" })
                @Html.EditorFor(m => m.Phone, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(m => m.Specialization, htmlAttributes: new { @class = "form-control" })
                @Html.EditorFor(m => m.Specialization, new { htmlAttributes = new { @class = "form-control" } })
                <input type="submit" value="Add Doctor" class="btn btn-primary" />
            }
        </div>
    </div>

    <div>
        @Html.ActionLink("View Doctor List", "Index", "Doctor")
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

ClinicManagementProject-main/Views/Doctor/Edit.cshtml
@model ClinicManagementProject.Models.Doctor

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/bootstrap.css" rel="stylesheet" />
    <title>Edit</title>
</head>
<body>

<h4>Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Edit", "Doctor", FormMethod.Post))
        {
            @Html.LabelFor(m => m.Doctor_Id, htmlAttributes: new { @class = "form-control" })
            @Html.HiddenFor(m => m.Doctor_Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.LabelFor(m => m.Username, htmlAttributes: new { @class = "form-control" })
            @Html.EditorFor(m => m.Username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.LabelFor(m => m.Name, htmlAttributes: new { @class = "form-control" })
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.LabelFor(m => m.Gender, htmlAttributes: new { @class = "form-control" })
            @Html.EditorFor(m => m.Gender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.LabelFor(m => m.Age, htmlAttributes: new { @class = "form-control" })
            @Html.EditorFor(m => m.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.LabelFor(m => m.Phone, htmlAttributes: new { @class = "form-control" })
            @Html.EditorFor(m => m.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.LabelFor(m => m.Specialization, htmlAttributes: new { @class = "form-control" })
            @Html.EditorFor(m => m.Specialization, new { htmlAttributes = new { @class = "form-control" } })
           <input type="submit" value="Update Doctor" class="btn btn-primary" />

        }
        
    </div>
</div>

<div>
    @Html.ActionLink("View Doctor List", "Index", "Doctor")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

ClinicManagementProject-main/Views/Doctor/Index.cshtml
@model IEnumerable<ClinicManagementProject.Models.Doctor>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        <a href="Doctor/Create">Create New</a><br />
        
    </p>
<table border="1">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialization)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialization)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Doctor_Id" href=Doctor/Edit?id=@item.Doctor_Id>Edit</a> |

            </td>
        </tr>
}
    </tbody>
</table>
<p>
    <a href="Home/Index">Back to Home</a>
</p>
</body>
</html>

ClinicManagementProject-main/Views/Home/Index.cshtml
@{Layout = "~/views/Shared/_Layout.cshtml";}

<body>

    <table class="table table-light table-bordered" width="100%" height="80%">
        <tr>
            <td>
                <div style="top:0px; border:1px solid red;">
                    <table border="0" align="center">
                        <tr height="100%">
                            <td height="70%" width="50%" valign="middle" align="center">
                                <h1>WELCOME TO FAMILY CLINIC </h1><br /> <h3>Your Health is Paramount to us</h3>
                                <br />
                                <h5>Doctor Creation Application</h5>
                            </td>

                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>



</body>

ClinicManagementProject-main/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/bootstrap.css" rel="stylesheet" />
    <style>
        #main {
            text-align: center;
        }

        #loginSection {
            width: 300px;
        }
    </style>
    <title>@ViewBag.Title</title>

</head>

<body>
    <div>
        <div>
            <h1 id="main" class="alert alert-success">CLINIC MANAGEMENT</h1>
            <section id="loginSection"></section>

        </div>
        <div>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                        </li>
                        &nbsp;&nbsp;&nbsp;

                        <span class="navbar-brand"></span>
                        <li class="nav-item">
                            @Html.ActionLink("Create Doctor", "Create", "Doctor", null, new { @class = "nav-link" })
                        </li>

               &nbsp;&nbsp;&nbsp;

                       
                    </ul>
                </div>
            </nav>
        </div>
        <div>
            @RenderBody()
        </div>

    </div>
</body>
</html>